### ISSUE TITLE
uneven shapes of `*.wdat` files

### ISSUE THREAD

**Issue by Belyor** [forbes-group/wdata#1]
The issue is that MPI terminated the process before some `*wdat` files has been saved to hard disc. This results in different shapes of `Var`s, in example: 
- `*rho_p.wdat` has a shape of _(4499, 24, 24, 64)_
- `*rho_n.wdat` has a shape of _(4500, 24, 24, 64)_

Is there a way to truncate all `Var`s to smallest size? 
`check_data` argument is set to be `False` yet Python (3.8 in my case) does not allow me to run the code, even when I do not reach to more than **2000** cycle.

I have tried to resolve it with `numpy.resize` but could not figure it out what should be the parameters.

**Comment by mforbes** [comment]
If you want to truncate, you should slice rather than resize:  `rho_n[:4499, ...]` for example.  I will have to look a little more closely to see how we can deal with incomplete data.  Can you please open an issue on the GitLab repo (this is just a mirror for convenience):

https://gitlab.com/coldatoms/utilities/wdata/-/issues

**Comment by Belyor** [comment]
Done. Ready to close. See **https://gitlab.com/coldatoms/utilities/wdata/-/issues/15** for continuation.
